export const POSTS = [
  {
    _id: "1",
    text: "Let's build a fullstack WhatsApp clone with NEXT.JS 14 😍",
    img: "/posts/post1.png",
    user: {
      username: "johndoe",
      profileImg: "/avatars/cat.png",
      fullName: "John Doe",
    },
    comments: [
      {
        _id: "1",
        text: "Nice Tutorial",
        user: {
          username: "janedoe",
          profileImg: "/avatars/chicken.png",
          fullName: "Jane Doe",
        },
      },
    ],
    likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
  },
  {
    _id: "2",
    text: "How you guys doing? 😊",
    user: {
      username: "johndoe",
      profileImg: "/avatars/dog.png",
      fullName: "John Doe",
    },
    comments: [
      {
        _id: "1",
        text: "Nice Tutorial",
        user: {
          username: "janedoe",
          profileImg: "/avatars/rabbit.png",
          fullName: "Jane Doe",
        },
      },
    ],
    likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
  },
  {
    _id: "3",
    text: "Astronaut in a room of drawers, generated by Midjourney. 🚀",
    img: "/posts/post2.png",
    user: {
      username: "johndoe",
      profileImg: "/avatars/owl.png",
      fullName: "John Doe",
    },
    comments: [],
    likes: [
      "6658s891",
      "6658s892",
      "6658s893",
      "6658s894",
      "6658s895",
      "6658s896",
    ],
  },
  {
    _id: "4",
    text: "I'm learning GO this week. Any tips? 🤔",
    img: "/posts/post3.png",
    user: {
      username: "johndoe",
      profileImg: "/avatars/owl.png",
      fullName: "John Doe",
    },
    comments: [
      {
        _id: "1",
        text: "Nice Tutorial",
        user: {
          username: "janedoe",
          profileImg: "/avatars/puffer-fish.png",
          fullName: "Jane Doe",
        },
      },
    ],
    likes: [
      "6658s891",
      "6658s892",
      "6658s893",
      "6658s894",
      "6658s895",
      "6658s896",
      "6658s897",
      "6658s898",
      "6658s899",
    ],
  },
];

export const USERS_FOR_RIGHT_PANEL = [
  {
    _id: "1",
    fullName: "John Doe",
    username: "johndoe",
    profileImg: "/avatars/dog.png",
  },
  {
    _id: "2",
    fullName: "Jane Doe",
    username: "janedoe",
    profileImg: "/avatars/chicken.png",
  },
  {
    _id: "3",
    fullName: "Bob Doe",
    username: "bobdoe",
    profileImg: "/avatars/owl.png",
  },
  {
    _id: "4",
    fullName: "Daisy Doe",
    username: "daisydoe",
    profileImg: "/avatars/rabbit.png",
  },
];
